### ISSUE TITLE
Other person can't type when sharing through MS Teams

### ISSUE THREAD

**Issue by okon3** [tom-englert/RegionToShare#63] opened 2023-09-21 13:15 UTC
**Environment**
- Operating System: Win10
- Collaboration Tool: Teams

**Describe the bug**
When sharing Region To Share through MS Teams and giving control to someone in the call they can use the mouse and both click and right click but they can't type.

**To Reproduce**
- Share Region To Share through MS Teams
- Give control to other person
- Ask them to type

**Expected behavior**
What they type when they have control should get typed on my pc

**Comment by tom-englert** [comment] 2023-09-21 15:16
That's by design; what they see is just a "video" of the shared region, so they type into this RTS "video"

duplicate of #52, #23

**Closed by tom-englert** 2023-09-21 15:16 UTC
Labels: duplicate
