### ISSUE TITLE
Integrate with Microsoft PowerToys

### ISSUE THREAD

**Issue by QuickScoP3s** [tom-englert/RegionToShare#74] opened 2024-05-17 08:39 UTC
Would be awesome if you could integrate this as a PowerToys:
https://github.com/microsoft/PowerToys

They already have their "Fancy Zones", but being able to share a zone would be amazing 💪

Maybe you could help with this ticket:
https://github.com/microsoft/PowerToys/issues/2774

**Comment by tom-englert** [comment] 2024-05-17 11:10
Duplicate of #61

**Closed** 2024-06-20 07:46 UTC
