### ISSUE TITLE
"Take-Control" freezes shared screen for other participant

### ISSUE THREAD

**Issue by PhilipqI** [tom-englert/RegionToShare#52] opened 2023-03-24 10:52 UTC
### Environment

Operating System: (Win10)
Collaboration Tool: (Teams)

### Describe the bug
When I´m sharing my screen and the other participant tries to take control (to show something on my screen) within Teams the shared screen freezes for him. 
As a result the "Take-Control" feature in Teams is not usable in combination with this great Tool :-(

### To Reproduce
Start region to share.
Share part of screen within Teams via share "RegionToShare"-App.
Other participant needs to ask for control.
Grant control on your teams.
Other participant can´t see sharing any longer, "Take-Control" failed.

### Expected behavior
It is expected that the other participant can take control and show stuff on my sharing.

**Comment by tom-englert** [comment] 2023-03-24 12:57
Duplicate of #23 
You are not sharing the original app, you are sharing just a "video" of the screen region, that's why this can never work.

**Closed by tom-englert** 2023-03-24 12:57 UTC
