### ISSUE TITLE
Remember the screen location and size. 

### ISSUE THREAD

**Issue by ChadThomsen** [tom-englert/RegionToShare#25] opened 2022-04-01 19:05 UTC
**Is your feature request related to a problem? Please describe.**
No

Would like to have the application "remember" its window size and location.  That way I don't have to resize it and and move it every time I open it.  Or make it so you can save the location and size settings in the .config file if possible.  This would save a lot of time over the course of many meetings and screen shares I do.  Keep up the good work as this is a cool app.

**Comment by tom-englert** [comment] 2022-04-02 06:54
Duplicate of #11

**Closed** 2022-04-02 06:55 UTC
Labels: duplicate
